var hierarchy =
[
    [ "anonymous_namespace{column.cxx}::BroadcastBroadcastersHandler", "classanonymous__namespace_02column_8cxx_03_1_1_broadcast_broadcasters_handler.html", null ],
    [ "anonymous_namespace{column.cxx}::CalcAfterLoadHandler", "classanonymous__namespace_02column_8cxx_03_1_1_calc_after_load_handler.html", null ],
    [ "anonymous_namespace{column.cxx}::CalcAllHandler", "structanonymous__namespace_02column_8cxx_03_1_1_calc_all_handler.html", null ],
    [ "anonymous_namespace{column.cxx}::CheckVectorizationHandler", "classanonymous__namespace_02column_8cxx_03_1_1_check_vectorization_handler.html", null ],
    [ "anonymous_namespace{column.cxx}::CompileAllHandler", "classanonymous__namespace_02column_8cxx_03_1_1_compile_all_handler.html", null ],
    [ "anonymous_namespace{column.cxx}::CompileErrorCellsHandler", "classanonymous__namespace_02column_8cxx_03_1_1_compile_error_cells_handler.html", null ],
    [ "anonymous_namespace{column.cxx}::CompileXMLHandler", "classanonymous__namespace_02column_8cxx_03_1_1_compile_x_m_l_handler.html", null ],
    [ "anonymous_namespace{column.cxx}::CopyAsLinkHandler", "classanonymous__namespace_02column_8cxx_03_1_1_copy_as_link_handler.html", null ],
    [ "anonymous_namespace{column.cxx}::CopyByCloneHandler", "classanonymous__namespace_02column_8cxx_03_1_1_copy_by_clone_handler.html", null ],
    [ "anonymous_namespace{column.cxx}::CopyTextAttrToClipHandler", "classanonymous__namespace_02column_8cxx_03_1_1_copy_text_attr_to_clip_handler.html", null ],
    [ "anonymous_namespace{column.cxx}::CopyToClipHandler", "classanonymous__namespace_02column_8cxx_03_1_1_copy_to_clip_handler.html", null ],
    [ "anonymous_namespace{column.cxx}::DeleteTabUpdater", "classanonymous__namespace_02column_8cxx_03_1_1_delete_tab_updater.html", null ],
    [ "anonymous_namespace{column.cxx}::FindEditCellsHandler", "classanonymous__namespace_02column_8cxx_03_1_1_find_edit_cells_handler.html", null ],
    [ "anonymous_namespace{global.cxx}::GetMutex", "structanonymous__namespace_02global_8cxx_03_1_1_get_mutex.html", null ],
    [ "anonymous_namespace{column.cxx}::InsertAbsTabUpdater", "classanonymous__namespace_02column_8cxx_03_1_1_insert_abs_tab_updater.html", null ],
    [ "anonymous_namespace{column.cxx}::InsertTabUpdater", "classanonymous__namespace_02column_8cxx_03_1_1_insert_tab_updater.html", null ],
    [ "anonymous_namespace{column.cxx}::MoveTabUpdater", "classanonymous__namespace_02column_8cxx_03_1_1_move_tab_updater.html", null ],
    [ "sc::anonymous_namespace{PivotTableFormatOutput.cxx}::NameResolver", "classsc_1_1anonymous__namespace_02_pivot_table_format_output_8cxx_03_1_1_name_resolver.html", null ],
    [ "anonymous_namespace{column.cxx}::NoteCaptionUpdater", "classanonymous__namespace_02column_8cxx_03_1_1_note_caption_updater.html", null ],
    [ "INetURLObject::PrefixInfo", "struct_i_net_u_r_l_object_1_1_prefix_info.html", null ],
    [ "anonymous_namespace{column.cxx}::RecalcOnRefMoveCollector", "classanonymous__namespace_02column_8cxx_03_1_1_recalc_on_ref_move_collector.html", null ],
    [ "anonymous_namespace{column.cxx}::ResetChangedHandler", "structanonymous__namespace_02column_8cxx_03_1_1_reset_changed_handler.html", null ],
    [ "anonymous_namespace{fillinfo.cxx}::RowInfoFiller", "classanonymous__namespace_02fillinfo_8cxx_03_1_1_row_info_filler.html", null ],
    [ "INetURLObject::SchemeInfo", "struct_i_net_u_r_l_object_1_1_scheme_info.html", null ],
    [ "anonymous_namespace{colorscale.cxx}::ScIconSetBitmapMap", "structanonymous__namespace_02colorscale_8cxx_03_1_1_sc_icon_set_bitmap_map.html", null ],
    [ "anonymous_namespace{column.cxx}::SetDirtyAfterLoadHandler", "structanonymous__namespace_02column_8cxx_03_1_1_set_dirty_after_load_handler.html", null ],
    [ "anonymous_namespace{column.cxx}::SetDirtyHandler", "classanonymous__namespace_02column_8cxx_03_1_1_set_dirty_handler.html", null ],
    [ "anonymous_namespace{column.cxx}::SetDirtyIfPostponedHandler", "structanonymous__namespace_02column_8cxx_03_1_1_set_dirty_if_postponed_handler.html", null ],
    [ "anonymous_namespace{column.cxx}::SetDirtyOnRangeHandler", "classanonymous__namespace_02column_8cxx_03_1_1_set_dirty_on_range_handler.html", null ],
    [ "anonymous_namespace{column.cxx}::SetDirtyVarHandler", "structanonymous__namespace_02column_8cxx_03_1_1_set_dirty_var_handler.html", null ],
    [ "anonymous_namespace{column.cxx}::SetTableOpDirtyOnRangeHandler", "classanonymous__namespace_02column_8cxx_03_1_1_set_table_op_dirty_on_range_handler.html", null ],
    [ "anonymous_namespace{column.cxx}::SharedTopFormulaCellPicker", "classanonymous__namespace_02column_8cxx_03_1_1_shared_top_formula_cell_picker.html", [
      [ "anonymous_namespace{column.cxx}::FormulaGroupPicker", "classanonymous__namespace_02column_8cxx_03_1_1_formula_group_picker.html", null ],
      [ "anonymous_namespace{column.cxx}::UpdateRefExpandGroupBoundChecker", "classanonymous__namespace_02column_8cxx_03_1_1_update_ref_expand_group_bound_checker.html", null ],
      [ "anonymous_namespace{column.cxx}::UpdateRefGroupBoundChecker", "classanonymous__namespace_02column_8cxx_03_1_1_update_ref_group_bound_checker.html", null ]
    ] ],
    [ "anonymous_namespace{column.cxx}::TabNoSetter", "classanonymous__namespace_02column_8cxx_03_1_1_tab_no_setter.html", null ],
    [ "anonymous_namespace{column.cxx}::UpdateCompileHandler", "classanonymous__namespace_02column_8cxx_03_1_1_update_compile_handler.html", null ],
    [ "anonymous_namespace{column.cxx}::UpdateGrowHandler", "classanonymous__namespace_02column_8cxx_03_1_1_update_grow_handler.html", null ],
    [ "anonymous_namespace{column.cxx}::UpdateRefOnCopy", "classanonymous__namespace_02column_8cxx_03_1_1_update_ref_on_copy.html", null ],
    [ "anonymous_namespace{column.cxx}::UpdateRefOnNonCopy", "classanonymous__namespace_02column_8cxx_03_1_1_update_ref_on_non_copy.html", null ],
    [ "anonymous_namespace{column.cxx}::UpdateTransHandler", "classanonymous__namespace_02column_8cxx_03_1_1_update_trans_handler.html", null ],
    [ "anonymous_namespace{column.cxx}::UsedRangeNameFinder", "classanonymous__namespace_02column_8cxx_03_1_1_used_range_name_finder.html", null ]
];